[package]
name = "mcugb"
version = "0.1.0"
authors = ["Victor Aguilar <victoraguilar90@gmail.com>"]
edition = "2018"
repository = "https://github.com/vaguilar/mcugb/"

[build-dependencies]
pkg-config = "0.3.34"

[dependencies]
bitmask-enum = "2.2.5"
clap = { version = "4.6", features = [ "derive" ] }
memmap2 = "0.9.11"
sdl2 = "0.38"
