[package]
name = "mcugb"
version = "0.1.0"
authors = ["Victor Aguilar <victoraguilar90@gmail.com>"]
edition = "2018"
repository = "https://github.com/vaguilar/mcugb/"

[dependencies]
sdl2 = "0.34"
memmap = "0.7.0"